name: goSample
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Application Docker image
        run: docker build . --file Dockerfile --tag server:$(date +%s)
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Test the Application Docker image
          run: docker-compose -f docker-compose.test.yml up -d
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Push image to ECR
        run: echo "Sample push to ECR"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy app to Kubernetes
        run: echo "Deployment is running ...."
      - name: Connect to EKS
        run: aws eks --region <region> update-kubeconfig --name <cluster_name>
      - name: run deployment
        run: kubectl apply -f ./kube-config/app-postgres-deployment.yaml -f ./kube-config/postgres-db-deploy.yaml -f ./kube-config/postgres-db-pv.yaml -f ./kube-config/postgres-secret.yaml